theme = "solarized_dark"

[editor]
line-number = "relative"
true-color = true
bufferline = "always"
color-modes = true

[editor.lsp]
display-messages = true

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]